X(ILLEGAL, "ILLEGAL")
X(EOF, "EOF")

X(IDENT, "IDENT")
X(INT, "INT")
X(STRING, "STRING")

X(ASSIGN, "=")
X(PLUS, "+")
X(MINUS, "-")
X(BANG, "!")
X(ASTERISK, "*")
X(SLASH, "/")

X(LT, "<")
X(GT, ">")
X(EQ, "==")
X(NOT_EQ, "!=")

X(COMMA, ",")
X(SEMICOLON, ";")

X(LPAREN, "(")
X(RPAREN, ")")
X(LBRACE, "{")
X(RBRACE, "}")

X(FUNCTION, "FUNCTION")
X(LET, "LET")
X(TRUE, "TRUE")
X(FALSE, "FALSE")
X(IF, "IF")
X(ELSE, "ELSE")
X(RETURN, "RETURN")
